[tool.poetry]
name = "fraud-detection-v3"
version = "0.1.0"
description = "Real-time Fraud Detection System with MLOps and XAI"
authors = ["TejasweeSulekh <20d070082@iitb.ac.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
xgboost = "^2.0.3"
mlflow = "^2.14.1"
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
shap = "^0.44.0"
scikit-learn = "^1.5.0"
pandas = "^2.2.0"
numpy = "<2.0.0"
requests = "^2.31.0"
redis = "^5.0.1"
confluent-kafka = "^2.3.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.25"
# MOVED THESE INSIDE THE DEPENDENCY BLOCK:
streamlit = "^1.31.0"
plotly = "^5.18.0"
watchdog = "^4.0.0"
gdown = "^5.1.0" # Added to down google drive for loading the data
langchain = "^1.2.10"
python-dotenv = "^1.2.1"
langchain-google-genai = "^4.2.1"
langgraph = "^1.0.9"
pgvector = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"