apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-init-model
spec:
  template:
    spec:
      containers:
      - name: init-model
        image: fraud-base:latest
        imagePullPolicy: Never # Use your local Docker build
        command: ["python", "src/ml/train_in_docker.py"]
        # This automatically loads all variables from your ConfigMap!
        envFrom:
        - configMapRef:
            name: fraud-config
      restartPolicy: Never
  backoffLimit: 2 # If it fails, retry twice before giving up