version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"

  kafka:
    image: bitnami/kafka:3.3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami/kafka"
    depends_on:
      - zookeeper

  transaction-api:
    build: ./transaction-api
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TRANSACTIONS_TOPIC=transactions
      - RESULTS_TOPIC=transaction-results
    depends_on:
      - kafka

  fraud-detector:
    build: ./fraud-detector
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TRANSACTIONS_TOPIC=transactions
      - RESULTS_TOPIC=transaction-results
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
